[package]
name = "tf"
version = "0.1.0"
edition = "2021"
authors = [
    "Adam McDaniel",
    "Vicky Chakpuang",
    "Logan Wrinkle",
    "Cade Walker"
]
description = "A collection of the compiler tools for a high level language that compiles to brainfuck."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
lalrpop = { version = "0.19", features = ["lexer"] }

[dependencies]
comment = "0.1.1"
lalrpop-util = "0.19"
lalrpop = { version = "0.19", features = ["lexer"] }
clap = "2.33"